
DROP TABLE IF EXISTS payment_orders;
CREATE TABLE `payment_orders` (
	`order_id`  bigint(20) NOT NULL COMMENT '支付单号',
	`app_id`  bigint(20) NOT NULL COMMENT '订单程序编号',
	`business_type`  varchar(32) NOT NULL DEFAULT '' COMMENT '业务类型',
	`company_id`  varchar(32) NOT NULL DEFAULT '' COMMENT '公司编号',
	`business_no`  varchar(32) NOT NULL DEFAULT '' COMMENT '业务单号',
	`receipt_no`  varchar(32) NOT NULL DEFAULT '' COMMENT '收款单号',
	`receipt_amount`  decimal(16,4) NOT NULL DEFAULT 0.0 COMMENT '收款金额',
	`receipt_summary`  varchar(200) NOT NULL DEFAULT '' COMMENT '收款摘要',
	`receipt_user_id`  varchar(20) NOT NULL DEFAULT '' COMMENT '收款人编号',
	`receipt_user_name`  varchar(20) NOT NULL DEFAULT '' COMMENT '收款人名称',
	`invoice_type`  varchar(10) NOT NULL DEFAULT 'NONE' COMMENT '发票类型(NONE: 无发票, PLAIN: 普通发票, VAT: 增值税发票)',
	`pay_method`  varchar(10) NOT NULL DEFAULT '' COMMENT '支付方式(WEIXIN: 微信支付, ALIPAY: 支付宝, BANKCARD: 刷银行卡, UNIONQR: 银联二维码',
	`customer_id`  varchar(20) NOT NULL DEFAULT '' COMMENT '客户编号',
	`customer_name`  varchar(200) NOT NULL DEFAULT '' COMMENT '客户名称',
	`order_time`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '订单日期',
	`order_month_key` int(11) NOT NULL DEFAULT 0 COMMENT '订单月份(eg:201811)',
	`order_status`  varchar(10) NOT NULL DEFAULT 'NONE' COMMENT '订单状态(NONE: 未支付, PAYING: 支付中, SUCCEED: 支付成功, FAILED: 支付失败, CANCELED: 支付取消, REFUNDED: 已退款',
    `auth_account`  varchar(100) NULL DEFAULT NULL COMMENT '支付授权码',
	`pay_time`  datetime NULL DEFAULT NULL COMMENT '支付日期',
	`pay_complete_time`  datetime NULL DEFAULT NULL COMMENT '支付完成日期',
	`bank_order_no`  varchar(32) NULL DEFAULT NULL COMMENT '银行订单流水号',
	`bank_trade_account`  varchar(32) NULL DEFAULT NULL COMMENT '银行交易账号',
    `bank_trade_result`  varchar(4000) NULL DEFAULT NULL COMMENT '收款机构原始交易数据',
	`bank_status_code`  int(11) NULL DEFAULT NULL COMMENT '银行状态码',
	`bank_status_msg`  varchar(200) NULL DEFAULT NULL COMMENT '银行状态描述',
	`bank_parameters` varchar(250) NULL DEFAULT NULL COMMENT '银行支付参数',
	`created_at`  datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
	`updated_at`  datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改日期',
	`created_by`  varchar(20) NULL DEFAULT '' COMMENT '创建人',
	`updated_by`  varchar(20) NULL DEFAULT '' COMMENT '修改人',
	CONSTRAINT `pk_payment_orders_order_id` PRIMARY KEY (`order_id`),
	UNIQUE INDEX `uk_payment_orders_business_receipt_no` (`business_no`, `receipt_no`) USING BTREE 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
